// 5. Design a system for XYZ Bank for storing account details, 
// Every account will have type either saving account or current account 
// For every account interest rate and minimum balance need to be stored.
// Interest rate for saving account is 4% and for current account 1%
// Minimum balance for saving account will be 20000 and current account will be 1000
// For each account store account holder details(fname, lname, mobile, email) 
// id will be autogenerated 3 letters of fname, 3letters of lname, count of account.
 
// If it’s a saving account, then store chequebooknumber
// If current account then store number of transactions/day, number of transactions will be different 
// for every account based on average annual balance in the account and will keep on changing based on how customer maintains the balance in the account.

#ifndef EMP_
#define EMP_

#include<cstring>

class Account{
    private:
        std::string id;
        char* fname;
        char* lname;
        long long int mobileno;
        char* email;
        static int accountCount;

    public:
        Account();
        Account(const char* fnm, const char* lnm, long long int mno, const char* e );

        ~Account();

        void setFname(const char* fnm);
        void setLname(const char* lnm);
        void setMobileno(long long int mno);
        void setEmail(const char* e);

        

        void display()const;

};

#endif
