// 5. Design a system for XYZ Bank for storing account details, 
// Every account will have type either saving account or current account 
// For every account interest rate and minimum balance need to be stored.
// Interest rate for saving account is 4% and for current account 1%
// Minimum balance for saving account will be 20000 and current account will be 1000
// For each account store account holder details(fname, lname, mobile, email) 
// id will be autogenerated 3 letters of fname, 3letters of lname, count of account.
 
// If it’s a saving account, then store chequebooknumber
// If current account then store number of transactions/day, number of transactions will be different 
// for every account based on average annual balance in the account and will keep on changing based on how customer maintains the balance in the account.

// Day 6 Assignment
// 1. modify Account class assignmnet
// create AccountService class and TestAccount.cpp
// in main method show following menu. and add all static functions to perform each operation
// "\n--- Account Management ---\n";
//         std::cout << "1. Add new account";
//         std::cout << "3. Display All Accounts\n";
//         std::cout << "4. Search by account number\n";
//         std::cout << "5. Search by Name\n";
//         std::cout << "6. Sort Accounts by balance\n";
//         std::cout << "7. Display All Saving Account\n";
//         std::cout << "8. Display All Current Account\n";
//         std::cout << "9. Exit\n";


#ifndef AP_
#define AP_

class Account{
    string id;
    char* fname;
    char* lname;
    long long int mobileno;
    long long int AccountNo;
    char* email;
    double balance;
    static int accountCount;

    public:
        Account();
        Account(const char* fnm, const char* lnm, long long int mno, long long int ano, const char* e, double b );
        ~Account();

        //setter methods
        void setFname(const char* fname);
        void setLname(const char* lname);
        void setMobileno(long long int mno);
        void setAccountno(long long int ano);
        void setBalance(double b);

        //Getter methods
        const char* getFname();
        const char* getLname();
        long long int getMobileno();
        long long int getAccountno();
        double getBalance();

        //Display method
        virtual void display();
};

#endif