#database properties
sql.connection.url=jdbc:mysql://localhost/advance_java
sql.connection.username=root
sql.connection.password=PG@1234Pass

#Sql queries
sql.category.insert=insert into Category values(?,?,?,?)
sql.category.findAll=select * from category
sql.category.findById=select * from category where categoryId=?